const dummySkillData =  [
        {
            "uid": 1,
            "name": "Frontend",
            "description": null,
            "skills": [
                {
                    "uid": 2,
                    "name": "Angular",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                   
                },
                {
                    "uid": 3,
                    "name": "CSS",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                 
                },
                {
                    "uid": 988,
                    "name": "Data Visualisation",
                    "description": null,
                    "createdAt": 1689853805157,
                    "altNames": null,
                
                },
                {
                    "uid": 4,
                    "name": "Deno",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                   
                },
                {
                    "uid": 1998,
                    "name": "Gatsby",
                    "description": null,
                    "createdAt": 1724318356879,
                    "altNames": null,
                 
                },
                {
                    "uid": 1962,
                    "name": "GOV.UK Design System",
                    "description": null,
                    "createdAt": 1722955942620,
                    "altNames": null,
                
                },
                {
                    "uid": 5,
                    "name": "HTML",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": "HyperText Markup Language",
                    
                },
                {
                    "uid": 858,
                    "name": "Material UI",
                    "description": null,
                    "createdAt": 1685021754886,
                    "altNames": null,
                  
                },
                {
                    "uid": 833,
                    "name": "NPM",
                    "description": null,
                    "createdAt": 1685021754886,
                    "altNames": "Node Package Manager",
                 
                },
                {
                    "uid": 1822,
                    "name": "OpenAPI",
                    "description": null,
                    "createdAt": 1715266387827,
                    "altNames": "Swagger",
                    
                },
                {
                    "uid": 6,
                    "name": "React",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                  
                },
                {
                    "uid": 7,
                    "name": "React Native",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                    
                },
                {
                    "uid": 993,
                    "name": "Vanilla JS",
                    "description": null,
                    "createdAt": 1689853805157,
                    "altNames": null,
                    
                },
                {
                    "uid": 850,
                    "name": "Vite",
                    "description": null,
                    "createdAt": 1685021754886,
                    "altNames": null,
                    
                },
                {
                    "uid": 8,
                    "name": "Vue.js",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                   
                },
                {
                    "uid": 841,
                    "name": "WCAG",
                    "description": null,
                    "createdAt": 1685021754886,
                    "altNames": "Web Content Accessibility Guidelines",
                   
                },
                {
                    "uid": 856,
                    "name": "Webpack",
                    "description": null,
                    "createdAt": 1685021754886,
                    "altNames": null,
                   
                },
                {
                    "uid": 9,
                    "name": "WPF",
                    "description": null,
                    "createdAt": 1677260573111,
                    "altNames": null,
                   
                }
            ]
        },
        {
            uid: 10,
            name: "Backend",
            description: null,
            skills: [
              {
                uid: 11,
                name: "Amazon DynamoDB",
                description: null,
                createdAt: 1677260573111,
                altNames: "AWS DynamoDB",
              },
              {
                uid: 12,
                name: "Amazon Elastic Container Service",
                description: null,
                createdAt: 1677260573111,
                altNames: "ECS, AWS ECS, Amazon ECS",
              },
              {
                uid: 13,
                name: "Amazon ElastiCache",
                description: null,
                createdAt: 1677260573111,
                altNames: "AWS ElastiCache",
              },
              {
                uid: 14,
                name: "Amazon RDS",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 15,
                name: "Amazon S3",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 16,
                name: "Amazon SQS",
                description: null,
                createdAt: 1677260573111,
                altNames: "AWS Simple Queuing Service",
              },
              {
                uid: 17,
                name: "Amazon Web Services",
                description: null,
                createdAt: 1677260573111,
                altNames: "AWS",
              },
              {
                uid: 839,
                name: "AMQP",
                description: null,
                createdAt: 1685021754886,
                altNames: "Advanced Message Queuing Protocol",
              },
              {
                uid: 18,
                name: "Apache Cassandra",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 19,
                name: "Apache Kafka",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 20,
                name: "Apache Spark",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 21,
                name: "Apache Tomcat",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 943,
                name: "API Design",
                description: null,
                createdAt: 1688558022981,
                altNames: null,
              },
              {
                uid: 854,
                name: "ASP.NET",
                description: null,
                createdAt: 1685021754886,
                altNames: null,
              },
              {
                uid: 22,
                name: "ASP.NET Core",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 990,
                name: "AWS Textract",
                description: null,
                createdAt: 1689853805157,
                altNames: null,
              },
              {
                uid: 23,
                name: "Azure",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 24,
                name: "Azure SQL",
                description: null,
                createdAt: 1677260573111,
                altNames: "Azure Structured Query Language",
              },
              {
                uid: 25,
                name: "BeautifulSoup",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 911,
                name: "Camunda",
                description: null,
                createdAt: 1687854152119,
                altNames: null,
              },
              {
                uid: 1076,
                name: "Data Migration",
                description: null,
                createdAt: 1696931091838,
                altNames: "Data Migration",
              },
              {
                uid: 26,
                name: "Django",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 937,
                name: "DoltDB",
                description: null,
                createdAt: 1688558022981,
                altNames: null,
              },
              {
                uid: 27,
                name: "ElasticSearch",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 1291,
                name: "Elixir",
                description: null,
                createdAt: 1709317527748,
                altNames: null,
              },
              {
                uid: 1293,
                name: "Erlang",
                description: null,
                createdAt: 1709317538902,
                altNames: null,
              },
              {
                uid: 1290,
                name: "FastAPI",
                description: null,
                createdAt: 1709317522530,
                altNames: null,
              },
              {
                uid: 945,
                name: "Git",
                description: null,
                createdAt: 1688558022981,
                altNames: null,
              },
              {
                uid: 28,
                name: "Golang",
                description: null,
                createdAt: 1677260573111,
                altNames: "Go",
              },
              {
                uid: 1098,
                name: "Gradle",
                description: null,
                createdAt: 1698245552893,
                altNames: null,
              },
              {
                uid: 941,
                name: "KeyDB",
                description: null,
                createdAt: 1688558022981,
                altNames: null,
              },
              {
                uid: 29,
                name: "Kibana",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 837,
                name: "Kustomize",
                description: null,
                createdAt: 1685021754886,
                altNames: null,
              },
              {
                uid: 30,
                name: "MariaDB",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 829,
                name: "Maven",
                description: null,
                createdAt: 1685021754886,
                altNames: null,
              },
              {
                uid: 31,
                name: "Microsoft SQL Server",
                description: null,
                createdAt: 1677260573111,
                altNames: "Microsoft Structured Query Language",
              },
              {
                uid: 32,
                name: "MongoDB",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 33,
                name: "MSMQ",
                description: null,
                createdAt: 1677260573111,
                altNames: "Microsoft Message Queuing",
              },
              {
                uid: 34,
                name: "MySQL",
                description: null,
                createdAt: 1677260573111,
                altNames: "",
              },
              {
                uid: 35,
                name: "Nginx",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 36,
                name: "Node.js",
                description: null,
                createdAt: 1677260573111,
                altNames: null,
              },
              {
                uid: 833,
                name: "NPM",
                description: null,
                createdAt: 1685021754886,
                altNames: "Node Package Manager",
              },
              {
                uid: 987,
                name: "ODBC",
                description: null,
                createdAt: 1689853805157,
                altNames: null,
              },
              {
                uid: 1822,
                name: "OpenAPI",
                description: null,
                createdAt: 1715266387827,
                altNames: "Swagger",
              },
            ],
          },
    ]

export {dummySkillData}